services:
  frontend:
    image: nginx:alpine
    volumes: 
      - ./frontend:/usr/share/nginx/html

  backend:
    image: backend
    container_name: backend
    build: ./backend
    command: sh -c "npm install && npm run dev"
    environment:
      - PG_DATABASE=${DB_DATABASE}
      - PG_USER=${DB_USER}
      - PG_PASSWORD=${DB_PASSWORD}
      - PG_HOST=${database}
      - GOOGLE_ID=${GOOGLE_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - FRONT_URL=${FRONT_URL}
    volumes:
      - ./backend:/backend

  database:
    image: database
    container_name: database
    build: ./database
    ports:
     - 5434:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  proxy:
    image: proxy
    build: ./proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/myconf.template:/etc/nginx/conf.d/default.conf
      - ./proxy/certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend

volumes:
  db_data:
